// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'mainMenu__item': string;
  'mainMenu__item1': string;
  'mainMenu__item2': string;
  'mainMenu__logo': string;
  'mainMenu__text': string;
  'mainMenu__userContainer': string;
  'mainMenu__userLink': string;
  'mainMenu__userName': string;
  'mainMenu__userQuest': string;
  'mainMenu__userbar': string;
  'mainMenu__wrapper': string;
  'mainMenu_bird': string;
  'mainMenu_ellipse1': string;
  'mainMenu_wrap': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
