// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'root': string;
  'root__expert_card': string;
  'root__wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
