// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'groupCard': string;
  'groupCardbox': string;
  'placeInGroupSelection': string;
  'placeInTalentSelection': string;
  'rateCard': string;
  'rateCardbox': string;
  'redCircle': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
