// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'img': string;
  'root': string;
  'root__group_collaborator_card': string;
  'root__group_collaborators': string;
  'root__person_card': string;
  'root__person_card_wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
