// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'cardDisabled': string;
  'content': string;
  'date': string;
  'header': string;
  'moduleCard': string;
  'modules': string;
  'root': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
