// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'root': string;
  'root_cursor_pointer': string;
  'root_type_cube': string;
  'root_type_horizont': string;
  'root_type_vertical': string;
}
export const cssExports: CssExports;
export default cssExports;
