// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card-0': string;
  'card-0_position': string;
  'card-1': string;
  'card-1_position': string;
  'card-2': string;
  'card-2_position': string;
  'card-3': string;
  'card-4': string;
  'card-5': string;
  'card-6': string;
  'card-6_position': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
