// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'preContent': string;
  'reviewWrapper': string;
  'userWidgetWrapper': string;
  'videoBox': string;
}
export const cssExports: CssExports;
export default cssExports;
