// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'root': string;
  'root__wrapper': string;
  'userData': string;
  'userData__fullname': string;
  'userData__position': string;
  'userPic': string;
}
export const cssExports: CssExports;
export default cssExports;
