// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'root': string;
  'root__btn': string;
  'root__btn_active': string;
}
export const cssExports: CssExports;
export default cssExports;
